# Generated by Django 4.1 on 2022-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0016_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
